

services:
  app:
    image: task-manager
    build: .
    container_name: backend
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      NODE_ENV: production
    ports:
      - "3000:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:${PORT}/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
